services:
  - type: web
    name: healthai-backend
    env: python
    rootDir: server
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -k gthread -t 120 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14

  - type: static
    name: healthai-frontend
    rootDir: .
    buildCommand: ""              # no build step
    staticPublishPath: .          # publish index.html, brain.html, lung.html, assets/
